# Generated by Django 5.0 on 2023-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('assgine_date', models.DateField()),
                ('is_complete', models.BooleanField()),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
